apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yml
  - service.yml
  - ingress.yml
  - rbac.yml

configMapGenerator:
  - name: logging-defaults
    literals:
      - LOGGER_TYPE=json
      - LOGGER_LEVEL=info

secretGenerator:
  - name: rooms-api
    env: config.properties
