apiVersion: v1
kind: ServiceAccount
metadata:
  name: gameserver-manager
  namespace: pictari-web
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gameserver-manager-cluster-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gameserver-manager-cluster-binding
subjects:
- kind: ServiceAccount
  name: gameserver-manager
  namespace: pictari-web
roleRef:
  kind: ClusterRole
  name: gameserver-manager-cluster-role
  apiGroup: rbac.authorization.k8s.io