apiVersion: v1
kind: ServiceAccount
metadata:
  name: gameserver-manager
  namespace: pictari-gameservers
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gameserver-manager-role
  namespace: pictari-gameservers
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gameserver-manager-binding
  namespace: pictari-gameservers
subjects:
- kind: ServiceAccount
  name: gameserver-manager
  namespace: pictari-gameservers
roleRef:
  kind: Role
  name: gameserver-manager-role
  apiGroup: rbac.authorization.k8s.io