apiVersion: v1
kind: Service
metadata:
  labels:
    app: rooms-api
    tier: front
  name: rooms-api
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: rooms-api
